name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.4.0
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check Rust formatting
      run: |
        cd rust-wasm
        echo "Running cargo fmt --check..."
        cargo fmt --check --verbose
        echo "Rust formatting check completed successfully"
    
    - name: Run Rust clippy
      run: |
        cd rust-wasm
        echo "Running cargo clippy..."
        cargo clippy -- -D warnings
        echo "Rust clippy check completed successfully"
    
    - name: Build WebAssembly
      run: |
        cd rust-wasm
        echo "Building WebAssembly with wasm-pack..."
        wasm-pack build --target web --out-dir ../pkg
        echo "WebAssembly build completed successfully"
        echo "Generated files:"
        ls -la ../pkg/
    
    - name: Build TypeScript
      run: |
        echo "Checking if WASM files are available..."
        ls -la pkg/
        echo "Building TypeScript with Vite..."
        npm run build
        echo "TypeScript build completed successfully"
    
    - name: Check TypeScript types
      run: |
        echo "Checking TypeScript types..."
        npx tsc --noEmit
        echo "TypeScript type check completed successfully"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.4.0
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build for GitHub Pages
      run: npm run build-pages
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
